apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: server
          image: ghcr.io/ggerganov/llama.cpp:server
          imagePullPolicy: Always
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
            - "--log-disable"
 